---
title: "Lethality Rate Neural Network"
author: "Team 3"
date: "7/25/2020"
output: html_document
---

```{r }
library(keras)
library(mlbench)
library(dplyr)
library(magrittr)
library(neuralnet)
library(MASS)
library(neuralnet)
```


```{r}
#looks at all test data
set.seed(123)
texas = Covid19_Texas_Data_lethality
maxValue = apply(texas , 2 , max)
minValue = apply(texas, 2, min)
texas = as.data.frame(scale(texas ,center = minValue , scale = maxValue - minValue )) #standardizes the values in the dataset
samp = sample(1:nrow(texas), 220) #MSE 0.005779216
samp2 = sample(1:nrow(texas), 220) #MSE 0.001815415
samp3 = sample(1:nrow(texas), 220) # MSE 0.0002075131
samp4 = sample(1:nrow(texas), 220) #MSE 0.05471535
samp5 = sample(1:nrow(texas), 220) #MSE  0.05911472
samp6 = sample(1:nrow(texas), 220) # MSE 0.001572894
samp7 = sample(1:nrow(texas), 220) # MSE 0.002089613
samp8 = sample(1:nrow(texas), 220) # MSE 0.0001646576
samp9 = sample(1:nrow(texas), 220) # MSE 0.0001610524
samp10 = sample(1:nrow(texas), 220) # MSE 0.0005962899
samp11 = sample(1:nrow(texas), 220)# MSE 0.0001700656
samp12 = sample(1:nrow(texas), 220) # MSE 0.04855424
samp13 = sample(1:nrow(texas), 220) # MSE 0.05687442
samp14 = sample(1:nrow(texas), 220) # MSE 0.002288181
samp15 = sample(1:nrow(texas), 220) # MSE 0.001279318
#Tested with quite a few rounds of 15, MSE consistently under 0.06
#Decided to showcase sample 10, not the best mse not the worst. 

texastrain = texas[samp10,] #allocating training data
texastest = texas[-samp10,] #allocating testing data

allVars = colnames(texas)
predictorVars = allVars[!allVars%in%"Lethality_Rate"]
predictorVars = paste(predictorVars,collapse = "+")
form = as.formula(paste("Lethality_Rate~", predictorVars, collapse = "+"))
neuraltexas = neuralnet(form , data = texastrain  , hidden = c(14,7,3), linear.output = T)
plot(neuraltexas, fontsize = 8 )
prediction = compute(neuraltexas , texastest[2:32])

prediction = prediction$net.result*(max(texastest$Lethality_Rate)-min(texastest$Lethality_Rate))+
  min(texastest$Lethality_Rate)

actualVal = (texastest$Lethality_Rate)*(max(texastest$Lethality_Rate)-min(texastest$Lethality_Rate))+
  min(texastest$Lethality_Rate)

MSE = sum((prediction - actualVal)^2)/nrow(texastest)
MSE
plot(prediction , actualVal , xlim = c(0,.2) , ylim = c(0,.2) , pch = 20 ,col = 'red', xlab = 'Predicted Values', ylab = 'Actual Values', title('Predicted vs Actual Values'))

sst = sum((texastest$Lethality_Rate - mean(texastest$Lethality_Rate))^2)
ssr = sum((prediction - mean(texastest$Lethality_Rate))^2)

R_square = 1 - (ssr/sst)
R_square

```


```{r}
#Uses lime for all test data
library(lime)
library(caret)
explainer = lime(texastrain, as_classifier(neuraltexas, labels = NULL))
explanation = explain(texastest, explainer, n_labels = 1, n_features = 32)
explanation


sorted_weights = explanation[c('feature','feature_weight')]
sorted_weights$feature_weight = abs(sorted_weights$feature_weight)
sorted_weights = sorted_weights[order(-sorted_weights$feature_weight),]
print(sorted_weights)
top_50 = sorted_weights[0:50,]
top_50_unique = unique(top_50$feature)
print((top_50_unique))

top_freq = table(top_50$feature)
top_freq

top_50 %>% 
group_by(feature) %>% 
summarise(n = n(),
          sum =sum(feature_weight))

```

```{r}

```

