---
title: "Lethality Rate Neural Network"
author: "Team 3"
date: "7/25/2020"
output: html_document
---

```{r }
library(keras)
library(mlbench)
library(dplyr)
library(magrittr)
library(neuralnet)
library(MASS)
```


```{r}
#looks at all test data
set.seed(123)
texas = Covid19_Texas_Data_lethality
maxValue = apply(texas , 2 , max)
minValue = apply(texas, 2, min)
texas = as.data.frame(scale(texas ,center = minValue , scale = maxValue - minValue )) #standardizes the values in the dataset
samp = sample(1:nrow(texas), 220)
texastrain = texas[samp,] #allocating training data
texastest = texas[-samp,] #allocating testing data

allVars = colnames(texas)
predictorVars = allVars[!allVars%in%"Lethality_Rate"]
predictorVars = paste(predictorVars,collapse = "+")
form = as.formula(paste("Lethality_Rate~", predictorVars, collapse = "+"))
neuraltexas = neuralnet(form , data = texastrain  , hidden = c(14,7,3), linear.output = T)
plot(neuraltexas, fontsize = 8)
prediction = compute(neuraltexas , texastest[2:32])

prediction = prediction$net.result*(max(texastest$Lethality_Rate)-min(texastest$Lethality_Rate))+
  min(texastest$Lethality_Rate)

actualVal = (texastest$Lethality_Rate)*(max(texastest$Lethality_Rate)-min(texastest$Lethality_Rate))+
  min(texastest$Lethality_Rate)

MSE = sum((prediction - actualVal)^2)/nrow(texastest)
MSE
plot(prediction , actualVal , xlim = c(0,.2) , ylim = c(0,.2) , pch = 20 ,col = 'blue')

sst = sum((texastest$Lethality_Rate - mean(texastest$Lethality_Rate))^2)
ssr = sum((prediction - mean(texastest$Lethality_Rate))^2)

R_square = 1 - (ssr/sst)
R_square

```


```{r}
#Uses lime for all test data
library(lime)
library(caret)
explainer = lime(texastrain, as_classifier(neuraltexas, labels = NULL))
explanation = explain(texastest[2:32], explainer, n_labels = 1, n_features = 31)
explanation

sorted_weights = explanation[c('feature','feature_weight')]
sorted_weights$feature_weight = abs(sorted_weights$feature_weight)
sorted_weights = sorted_weights[order(-sorted_weights$feature_weight),]
print(sorted_weights)
top_50 = sorted_weights[0:50,]
top_50_unique = unique(top_50$feature)
print((top_50_unique))

top_freq = table(top_50$feature)
top_freq

top_50 %>% 
group_by(feature) %>% 
summarise(n = n(),
          sum =sum(feature_weight))
```

```{r}


```

